newgml <- xmlTree("gml:FeatureCollection", namespaces = list(eing = "eing.foldhivatal.hu",gml = "http://www.opengis.net/gml"))
newgml$setNamespace("gml")
newgml$addNode("metaDataProperty", close = FALSE)
newgml$addNode("GenericMetaData", close = FALSE)
newgml$setNamespace(NULL)
newgml$addNode("MetaDataList", close = FALSE)
newgml$addNode("gmlID", "691da01c-7911-45a7-b831-bc594bfaca16")
newgml$addNode("gmlExportDate", round(as.numeric(Sys.time())*1000))
newgml$closeNode()
newgml$closeNode()
newgml$ycloseNode()
saveXML(newgml, "newgml.gml", prefix='<?xml version="1.0" encoding="UTF-8" standalone ="no"?>\n')
